# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions or plugins, check out
#     https://docs.fastlane.tools/actions
#     https://docs.fastlane.tools/plugins/available-plugins

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Internal Build to Play Store"
  lane :qa do
    gradle(
      task: 'assemble',
      flavor: 'qa',
      build_type: 'Release')
    upload_to_play_store(
      track: 'internal',
      package_name: "com.roycetownsend.magic_life.qa")
    # slack(message: 'Successfully distributed a new beta build')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
